import Head from "next/head";
import { Inter } from "@next/font/google";
import Hero from "../components/Hero";
import Link from "next/link";
import Image from "next/image";
import Intro from "@/components/Intro";
// import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Reliance Anodes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero
        heading="A World Leader in Cathodic Protection"
        message="Reliance Anodes are crafted from the highest quality MIL-Spec aluminum and zinc alloys, delivering reliable, long-lasting corrosion protection."
        img={"bg-img4"}
        tagline="Trusted worldwide. Proven to perform."
      />
      {/* "max-[600px]:bg-sky-300 min-[320px]:text-center */}
      <div className="bg-white flex flex-col justify-center items-center mt-0">
        <div className="w-[100%] h-[1050px] lg:h-[950px] lg:h-[850px] text-center bg-[#e7e9ec] flex flex-col min-[1075px]:flex-row">
          <Image
            src="/home/celebrating-square-banner.png"
            width="800"
            height="6000"
          />
          <div className="my-2 mx-8 md:mx-[5] text-xl xl:ml-[8%] min-[1250px]:text-3xl tracking-wide font-thin flex flex-col justify-center">
            <p>
              Reliance Anodes is a division of Metal Distributors Ltd., proudly serving the industry since 1949.
            </p>
            <p className="pt-4">
              Backed by decades of experience and skilled technicians, we’ve earned a global reputation for precision-crafted, high-performance anodes.
            </p>
            <p className="pt-4 pb-2">We use only trusted raw materials, and all our marine anodes meet <span className='font-bold'>U.S. Military Specifications</span>:
            </p>
            <p>
              <span className='font-bold'>MIL-A-18001</span> for zinc and <span className='font-bold'>MIL-A-24779</span> for aluminum.
            </p>
            <p className="pt-4">
              With Reliance Anodes, you’re getting more than protection—you’re getting performance you can count on.
            </p>
          </div>
        </div>

        <h2 className="mt-[10vw] lg:mt-[5vw]">Explore Our Expansive Collection of Anodes</h2>
        <p className="lg:text-3xl text-center py-6 px-2">From small recreational boats to large commercial vessels—and even underground infrastructure—we offer solutions for all your corrosion protection needs.</p>

        <div className="grid grid-cols-1 lg:grid-cols-3">
          <Link href="/products/commercial">
            <div className="relative">
              <Image
                src="/home/comm-1.png"
                width="300"
                height="300"
                className="mx-[10vw] my-[10vw] lg:mx-[5vw] lg:my-[5vw] rounded-xl"
              />
              <div className="flex justify-center w-full h-full items-center absolute top-0 left-0 right-0 bottom-0 rounded-xl group">
                <p className="hidden group-hover:block">
                  <Image
                    src="/home/comm-2.png"
                    width="300"
                    height="300"
                    className="mx-[10vw] my-[10vw] lg:mx-[5vw] lg:my-[5vw] rounded-xl"
                  />
                </p>
              </div>
            </div>
          </Link>

          <Link href="/products/pleasureCraft">
            <div className="relative">
              <Image
                src="/home/pc-1.png"
                width="300"
                height="300"
                className="mx-[10vw] my-[10vw] lg:mx-[5vw] lg:my-[5vw] rounded-xl"
              />
              <div className="flex justify-center w-full h-full items-center absolute top-0 left-0 right-0 bottom-0 rounded-xl group">
                <p className="hidden group-hover:block">
                  <Image
                    src="/home/pc-2.png"
                    width="300"
                    height="300"
                    className="mx-[10vw] my-[10vw] lg:mx-[5vw] lg:my-[5vw] rounded-xl"
                  />
                </p>
              </div>
            </div>
          </Link>

          <Link href="/products/zincCap">
            <div className="relative">
              <Image
                src="/home/zncap-1.png"
                width="300"
                height="300"
                className="mx-[10vw] my-[10vw] lg:mx-[5vw] lg:my-[5vw] rounded-xl"
              />
              <div className="flex justify-center w-full h-full items-center absolute top-0 left-0 right-0 bottom-0 rounded-xl group">
                <p className="hidden group-hover:block">
                  <Image
                    src="/home/zncap-2.png"
                    width="300"
                    height="300"
                    className="mx-[10vw] my-[10vw] lg:mx-[5vw] lg:my-[5vw] rounded-xl"
                  />
                </p>
              </div>
            </div>
          </Link>
        </div>

        <div className="flex justify-center py-10">
          <Link target="_blank" href="/RelianceCatalogue.pdf" locale={false}>
            <div className="relative">
              <Image
                src="https://user-images.githubusercontent.com/77664153/251527484-1e99e9c6-a883-4ad2-8e97-760c83f3f57d.png"
                alt="Click to view Product Catalogue Banner"
                className="min-w-[80px]"
                width={1500}
                height={800}
              />
              <div className="flex justify-center w-full h-full items-center absolute top-0 left-0 right-0 bottom-0 rounded-xl group">
                <div className="hidden group-hover:block">
                  <Image
                    src="https://user-images.githubusercontent.com/77664153/251814292-5c631d1d-bafd-48b9-8ea6-6447f153f4b8.png"
                    alt="Click to view Product Catalogue Banner"
                    className="min-w-[80px]"
                    width={1500}
                    height={800}
                  />
                </div>
              </div>
            </div>
          </Link>
        </div>
      </div>
    </>
  );
}

{
  /* <Hero heading="Don't let CORROSION eat into your investment" message='Demand Reliance Anodes' /> */
}
